# Matrix Multiplication

1. Two matirces can be multiplies if and only if they are M x N and  N x K. That means that if we have a 2 x 3 matrix and a 3 x 4 matrix we can multiply

In [1]:
# importing module
import numpy as np

In [4]:
M1 = np.round(5*np.random.randn(2,3))
M2 = np.round(3*np.random.randn(3,4))
M3 = np.round(4*np.random.randn(4,6))

print(np.matmul(M1,M2))

print(M1@M2)

[[  6. -12.  30.  49.]
 [ 40. -19.  68.  14.]]
[[  6. -12.  30.  49.]
 [ 40. -19.  68.  14.]]
