## Matrix

In [1]:
# importing module
import numpy as np

In [2]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [6]:
M= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

print(M)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
m1 = np.array([[1,2],[8,9]])

m2 = np.eye(2)

m3=np.array([[1,2,3],
             [4,5,6]])
print(m1*3)             

[[ 3  6]
 [24 27]]


In [11]:
print(m2*3)
np.add(m1,m2)

[[3. 0.]
 [0. 3.]]


array([[ 2.,  2.],
       [ 8., 10.]])