# Transposing Vectors and Matrices

In [1]:
#importing modules
import numpy as np

In [3]:
v1 = np.array([2,3,-1], ndmin=2)

print(v1)
print(v1.T)

[[ 2  3 -1]]
[[ 2]
 [ 3]
 [-1]]


In [15]:
M = np.round(7*np.random.randn(3,3))

print(M)
print(M.T)

[[  4.  -1.   5.]
 [ -5.   1.   0.]
 [  6.  -0. -10.]]
[[  4.  -5.   6.]
 [ -1.   1.  -0.]
 [  5.   0. -10.]]


Transposing a matrix twice means that you will get the initial matrix

In [17]:
N = np.round(7*np.random.randn(3,3))

NT = N.T

NTT = NT.T

print(N)
print(" ")
print(NT)
print(" ")
print(NTT)


[[ 3. 14. 19.]
 [-1.  9. -2.]
 [ 6. -8.  6.]]
 
[[ 3. -1.  6.]
 [14.  9. -8.]
 [19. -2.  6.]]
 
[[ 3. 14. 19.]
 [-1.  9. -2.]
 [ 6. -8.  6.]]
